[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/api/weather-proxy"
  to = "https://api.openweathermap.org/data/2.5/weather"
  status = 200
  force = true
  query = { appid = "0ff4b4aee450de38b133dce284102288", units = "metric" }
